apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments
        image: your-appointments-image:latest
        env:
        - name: YOUR_ENV_VARIABLE
          value: "your-value"
        # Add other environment variables as needed

        resources:
          limits:
            memory: "256Mi"  # Set your desired memory limit
            cpu: "100m"      # Set your desired CPU limit
          requests:
            memory: "128Mi"  # Set your desired memory request
            cpu: "50m"       # Set your desired CPU request

        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
